### ISSUE TITLE
(feat): Allow querying for all GravityFormsForm(s). 

### ISSUE THREAD

**Issue by ajmar** [harness-software/wp-graphql-gravity-forms#10]
The above would be useful (in my situation) for building all the forms at once without having to know each form id (challenging to get in Gatsby due to the inherent limitations of StaticQueries). Something similar is also seen in gatsby-source-gravityforms with `allGfForm`.

Example:
```graphql
{
  gravityFormsForms {
    formId
    ... // etc.
  }
}
```

**Comment by kellenmace** [comment]
Hey @ajmar,

I agree that this would be useful to have. Any chance you could take a crack at writing it and submit a PR?

- Ultimately, we need a new `gravityFormsForms` field registered on the `RootQuery` type.
- In its resolver, we should call `GFAPI::get_forms()` to get the forms and return an array of `GravityFormsForm`s. Documentation: https://docs.gravityforms.com/api-functions/#get-forms
- I think supporting pagination for this is probably advisable, too. If someone had 20+ forms and each one had hundreds of fields and they queried them all at once, that could potentially be a lot of data. So the ability to get forms data in smaller batches/pages could help with that.

**Comment by ajmar** [comment]
Hi @kellenmace , I've made a prototype implementation [here](https://github.com/ajmar/wp-graphql-gravity-forms/tree/all-forms), could you perhaps make a new branch on this repo before I submit a PR? (avoid polluting master until it's ready).

I've implemented the core functionality, it works & is able to query forms. Haven't yet implemented query arguments e.g where(), sorting, or pagination.

**Comment by kellenmace** [comment]
Hey @ajmar –

Thanks for your help on this one! I had a need arise at work for the ability to query for all forms, so I used your code as a starting point and finished adding support for the feature, including support for filtering by status and pagination.

I added a section to the documentation with an example query, if you want to check it out:
https://github.com/harness-software/wp-graphql-gravity-forms#get-a-list-of-forms

Thanks again 👍🏼
