### ISSUE TITLE
Add additional Name fields to the GraphQL Schema

### ISSUE THREAD

**Issue by kellenmace** [harness-software/wp-graphql-gravity-forms#101]
I noticed that `Prefix Choices` and `Default Values` have not yet been added to the schema for `Name` fields. It would be great to get them added.

## Screenshot

<img width="514" alt="name-fields" src="https://user-images.githubusercontent.com/5306336/116894539-2ecb8780-ac00-11eb-8efc-9b709ac8970f.png">

**Comment by justlevine** [comment]
What version of the plugin are you using?

This _should_ work:
```graphql
formFields {
  nodes {
    ... on NameField {
      inputs {
        defaultValue
        choices {
          isSelected
          text
          value
        }
      }
    }     
  }
}
```

![image](https://user-images.githubusercontent.com/29322304/116924831-5fbeb300-ac26-11eb-8028-6ce481e60ba1.png)

**Comment by kellenmace** [comment]
That works great– I overlooked the fact that the `defaultValue` & `choices` fields are available on each input. Thanks! 🙌
