### ISSUE TITLE
[Bug] - `fieldFilters` only searches first value in array. 

### ISSUE THREAD

**Issue by natac13** [harness-software/wp-graphql-gravity-forms#133]
## Is your feature request related to a problem? Please describe.
I am unable to search using the `fieldFilter` option and `key === 0`, using contains to match against all field array values

## Describe the solution you'd like
Be able to search entire field array values

![Screen Shot 2021-07-18 at 20 10 36](https://user-images.githubusercontent.com/10660283/126086568-83538a1e-8e25-4468-99ea-07473594ed97.png)
![Screen Shot 2021-07-18 at 20 11 10](https://user-images.githubusercontent.com/10660283/126086569-b0eed78a-4069-4bdb-a96d-5b09eccb1181.png)
![Screen Shot 2021-07-18 at 20 11 25](https://user-images.githubusercontent.com/10660283/126086570-5b0340fc-cccc-48fd-98bf-8e47af8f966b.png)

**Comment by justlevine** [comment]
`RootQueryEntriesResolver.php` needs to be refactored to comply with https://docs.gravityforms.com/api-functions/#get-entries

**Comment by justlevine** [comment]
Closed by https://github.com/harness-software/wp-graphql-gravity-forms/releases/tag/v0.8.0
