### ISSUE TITLE
[Feature Request] - Query for a form by Name and add name to where arg for forms query

### ISSUE THREAD

**Issue by natac13** [harness-software/wp-graphql-gravity-forms#134]
## Is your feature request related to a problem? Please describe.
I would like to be able to query for a form by the title of the form. Between clients a `formId` can change for the same form. Therefore I need a more specific way to target a form in a single and all query.

## Describe the solution you'd like
With:
`gravityFormsForm` I would like a `title` arg and not have to provide an `id` if I give the `title`
`gravityFormsForms` I would like a `title` field on the `where` argument to filter the queried list by

**Comment by justlevine** [comment]
Not sure how feasible this is from a plugin POV, as its not supported by Gravity Form's API. To filter by title, we'd need to first fetch all forms, and then loop through and compare the `$form['title']`.

If you're using this plugin on multisite, where the same form ostensibly has different `formIds`, you might be better served by creating a `wp_option` that correctly maps the site-specific formIds to your standardized frontend.
