### ISSUE TITLE
Compatibility with wp-graphql v0.8.0

### ISSUE THREAD

**Issue by hrosb** [harness-software/wp-graphql-gravity-forms#15]
Hi,

Thank you for your hard work with this plugin. I hope all is well with you guys during these special days.

Seems like v0.8.0 of wp-graphql introduced some breaking changes.
Details: 
https://github.com/wp-graphql/wp-graphql/releases/tag/v0.8.0

Specifically the changes to the AbstractConnectionResolver is breaking querying for fields inside a form. 

Probably #14 is releated to this. My error was very similar:
```Fatal error:  Class WPGraphQLGravityForms\Connections\FormFieldConnectionResolver contains 4 abstract methods and must therefore be declared abstract or implement the remaining methods (WPGraphQL\Data\Connection\AbstractConnectionResolver::get_loader_name, WPGraphQL\Data\Connection\AbstractConnectionResolver::get_ids, WPGraphQL\Data\Connection\AbstractConnectionResolver::is_valid_offset, ...) in (path)/wp-graphql-gravity-forms/src/Connections/FormFieldConnectionResolver.php on line 9```

Any work being done to update the plugin to work with the new version?

**Comment by Twansparant** [comment]
Jup, I'm running into the same issues.
Rolling back to **wp-graphql v0.7.1** fixed these errors.

**Comment by kellenmace** [comment]
Hi @hrosb & @Twansparant. Yes, the plugin does need to be updated to work with the new abstract connection resolver / deferred resolution model that WPGraphQL has introduced. I plan to push an update soon so that this plugin is once again compatible with the latest version of WPGrapQL.

**Comment by kellenmace** [comment]
@hrosb & @Twansparant: FYI – have updated the plugin to work with the latest version of WPGraphQL (0.12.3).
