### ISSUE TITLE
[Bug] File upload not permitted for security reasons

### ISSUE THREAD

**Issue by koraysels** [harness-software/wp-graphql-gravity-forms#159]
## Describe the bug
when I try to upload a form with a file i get 'This file type is not permitted for security reasons' 500 error.

[discussion thread here](https://github.com/harness-software/wp-graphql-gravity-forms/discussions/108#discussioncomment-1362592
)

## To Reproduce
this is my query:
```gql
  mutation SUBMIT_FORM_ENTRY($formId: Int!, $fieldValues: [FieldValuesInput]) {
    submitGravityFormsForm(
      input: {
        formId: $formId
        clientMutationId: "submitGfForm"
        fieldValues: $fieldValues
      }
    ) {
      clientMutationId
      entryId
      resumeToken
      resumeUrl
      entry {
        form {
          node {
            confirmations {
              message
            }
          }
        }
      }
    }
  }
```

and these are the variables: 

```json
{
    "formId": 2,
    "fieldValues": [
        {
            "id": 5,
            "value": "fweqwef"
        },
        {
            "id": 6,
            "value": "fqfqwf"
        },
        {
            "id": 7,
            "value": "fqwfqwf"
        },
        {
            "id": 8,
            "fileUploadValues": {
                "name": "Rataplan-straatzijde_20180328_EW46474_PHOTO-©-EDDY-WESTVEER-1024x576.jpeg",
                "type": "image/jpeg",
                "size": 162024,
                "tmp_name": "/var/folders/h6/2h8fnrtx1q7ddt18hm162_k80000gn/T/upload_a0051c2799aa83484fc63ae57ffc7a0f"
            }
        }
    ]
}
```

## Expected behavior
File upload to work and be recorded in the gravity forms entries. 

## Additional context

> 
> The error is being thrown [by our plugin](https://github.com/harness-software/wp-graphql-gravity-forms/blob/develop/src/Utils/GFUtils.php#L472), and is a result of [`wp_check_filtetype_and_ext()`](https://developer.wordpress.org/reference/functions/wp_check_filetype_and_ext/) coming back bad.
> 
> FYI: the `ALLOW_UNFILTERED_UPLOADS` only affects administrator roles, but since your example is JPG (which by default is allowed for all users), that shouldnt be the problem here.
> 
> Would you be able to add the following code to WP, and then share (in the issue you create) the output generated in debug.log?
> ```php
> add_filter( 
>   'wp_check_filetype_and_ext',
>   function ( array $file ) { error_log( print_r( $file, true) ); }
> );
> ```
> 
> Thanks!

_Originally posted by @justlevine in https://github.com/harness-software/wp-graphql-gravity-forms/discussions/108#discussioncomment-1362592_

**Comment by koraysels** [comment]
I added the filter and The result i get is the following $file object: 

```php
Array
(
    [ext] => "jpeg"
    [type] => "image/jpeg"
    [proper_filename] => false
)

```

**Comment by koraysels** [comment]
I went digging and found out that the issue is that the [handle_file_upload](https://github.com/harness-software/wp-graphql-gravity-forms/blob/b8bd074e81a7b8847a4a7d9dce472afb12978a03/src/Utils/GFUtils.php#L456-L469)

function that does the `wp_check_filetype_and_ext()` function does not supply the correct arguments. the `$file` argument in my case is just the filename `'0ataplan-straatzijde_20180328_EW46474_PHOTO-©-EDDY-WESTVEER-1024x576.jpeg'`. and the $target is 

```php
array (
  'path' => '/<mydirectory>/backend/web/app/uploads/gravity_forms/2-0739a791d7112d4b100586a188266eb0/2021/09/',
  'url' => 'https://<my-url>/app/uploads/gravity_forms/2-0739a791d7112d4b100586a188266eb0/2021/09',
  'subdir' => '/2021/09',
  'basedir' => '/<mydirectory>//backend/web/app/uploads/gravity_forms',
  'baseurl' => 'https://<my-directory>/app/uploads/gravity_forms',
)

```

this means that line 461 does has undefined values to check the filetype..  so the return value, $wp_filetype is 
```php
array (
  'ext' => false,
  'type' => false,
  'proper_filename' => false,
)

```

which of course is not really what we want..

**Comment by koraysels** [comment]
so @justlevine do you think it is a real bug in the plugin or is my usage wrong?

**Comment by justlevine** [comment]
@koraysels I'm struggling to replicate consistently. It could be an issue with the file/folder permissions (im guessing from the url structure that you're using bedrock?), or the way we check if the the field supports uploading multiple files.

On the bright side, its definitely _not_ an issue with the wp user having the proper permissions for the file type.

Can you:
1. share the permissions/ownership of `\tmp`, `...\app\uploads` and `app\uploads\gravityforms`?
2. confirm whether the File Upload Field has `multipleFiles` enabled?
3. wrap the `fileUploadValues in an array, like so:
```graphql
{
  "id": 8,
   "fileUploadValues": [ {
      "name": "Rataplan-straatzijde_20180328_EW46474_PHOTO-©-EDDY-WESTVEER-1024x576.jpeg",
       "type": "image/jpeg",
       "size": 162024,
       "tmp_name": "/var/folders/h6/2h8fnrtx1q7ddt18hm162_k80000gn/T/upload_a0051c2799aa83484fc63ae57ffc7a0f"
   } ]
}
```

Regardless of the cause, we definitely need to add a check and throw a _relevant_ error message.

**Comment by koraysels** [comment]
I am using bedrock indeed, 

1. my permissions: 
```
drwxr-xr-x   5 krockyhack  staff      160 Aug 13 10:02 uploads
drwxr-xr-x   5 krockyhack  staff  160 Sep 27 15:53 gravity_forms
```

2. I enabled and disable 'multiple files' a number of times during testing and it made no difference.
3. When I wrapo it in an Array I also get a 500. 
```
Variable "$fieldValues" got invalid value [{"id":5,"value":"rqrfqw"},{"id":6,"value":"fqwqwfr"},{"id":7,"value":"fqwfqwfqwf"},"[object File]"]; Expected type FieldValuesInput to be an object at value[3].
```

**Comment by koraysels** [comment]
So If I downgrade to `wp-graphql-gravity-forms: "^0.6"` it works for single file uploads but not for multiple

**Comment by justlevine** [comment]
@koraysels did you ever sort this out?

> Variable "$fieldValues" got invalid value [{"id":5,"value":"rqrfqw"},{"id":6,"value":"fqwqwfr"},{"id":7,"value":"fqwfqwfqwf"},"[object File]"]; Expected type FieldValuesInput to be an object at value[3].

> UPDATE: so If I use a multiple file form it seems that my mutation in Apollo converts a js File Object to a string "[object FIle]" now... which is very strange..

Both of these comments combined make it seem that the issue is what you are passing to your mutation. As I wrote [above](https://github.com/harness-software/wp-graphql-gravity-forms/issues/159#issuecomment-925043863), `fileUploadValues` takes an object with a specific set of keys and _is not identical_ to the JS File object generated. Rather you should get the data needed from the File object to create the object passed to GraphQL.

Making assumptions from the error message, your `FieldValuesInput` should look like this:

```graphql
{
  fieldValues: [
    {
      id: 5,
      value: "rqrfqw"
    },
    {
      id: 6,
      value: "fqwqwfr"
    },
    {
      id: 7, # This is your file upload field,
      fileUploadValues: [ {
        name: "Rataplan-straatzijde_20180328_EW46474_PHOTO-©-EDDY-WESTVEER-1024x576.jpeg",
        type: "image/jpeg",
        size: 162024,
        tmp_name: "/var/folders/h6/2h8fnrtx1q7ddt18hm162_k80000gn/T/upload_a0051c2799aa83484fc63ae57ffc7a0f"
      } ]
    }
  ]
}
```

**Comment by justlevine** [comment]
It's been a while, so I'm closing this issue. If its still relevant, ping me here and I'll reopen.
