### ISSUE TITLE
Move formField properties to Interfaces

### ISSUE THREAD

**Issue by justlevine** [harness-software/wp-graphql-gravity-forms#180]
Following emerging patterns in the ecosystem, and to keep our codebase dry and robust, we should migrate as many individual form-field properties over to GraphQL Interfaces. 

The logical grouping would be to follow whats defined in `GF_Field::get_form_editor_field_settings()`. This is the closest thing GF has to a definitive list of field properties, and ideally we'd be able to use that to then auto-register the correct interfaces to our `formFields`, drastically cutting down the code we need to define and test fields, and making it easier to support new ones.

**Comment by tinytoolbox** [comment]
Does this have any effect on custom fields that have been defined in GF?  For example, we've extended the file upload field in GF to specifically handle photos & the creation of a photo custom post type upon submission.  Apologies if I'm misunderstanding this item.

**Comment by justlevine** [comment]
@tinytoolbox This particular issue, no. 

However the [general v0.10.0 release](https://github.com/harness-software/wp-graphql-gravity-forms/milestone/5) and particularly #155 and #182 will ~possibly~ likely require some small changes to how the custom fields are registered to WPGraphQL.

**Comment by justlevine** [comment]
On further inspection, interfaces are unnecessary, and we can map field settings directly to the relevant properties. This approach will also allow us to automatically register _all active form fields_. The only thing required for unsupported form fields would be a `graphql_register_field()` call.

[These are the groupings of all core + currently supported extensions](https://docs.google.com/spreadsheets/d/1xY5WZakfzsT9EZjnQOvbgHHkgHYFrE4s3_Al96so8s4/edit?usp=sharing) (hidden rows have already been implemented [in the branch](https://github.com/justlevine/wp-graphql-gravity-forms/tree/chore/refactor-form-field-properties-to-interfaces)).
