### ISSUE TITLE
[Feature Request] Suggested Schema Changes

### ISSUE THREAD

**Issue by justlevine** [harness-software/wp-graphql-gravity-forms#185]
A stable GraphQL API should be [consistent, self-documenting](https://atheros.ai/blog/graphql-best-practices-for-graphql-schema-design), and [compatible with the rest of the WPGraphQL ecosystem](https://wp-graphql.slack.com/archives/C02AYA0KL9K/p1638031373033400) so as not to cause fatal errors when multiple plugins are used.

[For v1.0]((https://github.com/harness-software/wp-graphql-gravity-forms/issues/179)), we want the schema to be in a healthy place that won't require breaking changes _unless absolutely necessary_ (i.e. bugfixes). In a pre-v1.0 landscape, we want to group as many breaking changes into a single release. Since [v0.1.0](https://github.com/harness-software/wp-graphql-gravity-forms/milestone/5) already has over [250 breaking changes](https://gist.github.com/justlevine/911585c702aeca3c8f68fc64c85c664b) (most, to be fair are removing old deprecations) with more to come, now is a good time to evaluate other changes.

Below is a list of candidates for change. _Most (not all)_ of the old values can be deprecated until v1.0, although if we're already removing so much deprecated code (and making other breaking changes in the process), it might make sense to remove the old values entirely (i.e. ripping the bandaid off).

### Enum Type names. 
These are recommended to prevent fatal conflicts with other plugins.
- `AddressTypeEnum` => `AddressFieldTypeEnum` .
- `ButtonTypeEnum` => `FormButtonTypeEnum` .
- `CalendarIconTypeEnum` => `FormFieldCalendarIconTypeEnum` .
- `CaptchaThemeEnum` => `CaptchaFieldThemeEnum` .
- `CaptchaTypeEnum` => `CaptchaFieldTypeEnum` .
- `ConfirmationTypeEnum` => `FormConfirmationTypeEnum` .
- `DateTypeEnum` => `DateFieldTypeEnum` .
- `IdTypeEnum` => `{$type}IdTypeEnum` . **Note:** See `resumeToken`.
- `LabelPlacementPropertyEnum` => `FormLabelPlacementEnum` .
- `MinPasswordStrengthEnum` => `PasswordFieldMinStrengthEnum` .
- `NotificationToTypeEnum` => `FormNotificationToTypeEnum` .
- `PageProgressStyleEnum` => `FormPageProgressStyleEnum` .
- `PageProgressTypeEnum` => `FormPageProgressTypeEnum` .
- `QuizGradingTypeEnum` => `QuizFieldGradingTypeEnum` .
- `RequiredIndicatorEnum` => `FormRequiredIndicatorEnum` .
- `RuleOperatorEnum` => `FormRuleOperatorEnum` .
- `SignatureBorderStyleEnum` => `SignatureFieldBorderStyleEnum` .
- `SignatureBorderWidthEnum` => `SignatureFieldBorderWidthEnum` .
- `SizePropertyEnum` => `FormFieldSizeEnum` .
- `SizePropertyEnum` => `FormFieldSizeEnum` .
- `SortingInputEnum` => `SortDirectionEnum` .
- `VisibilityPropertyEnum` => `FormFieldVisibilityEnum` .

### Input type names.
These are recommended to prevent fatal conflicts with other plugins.

- `AddressInput` => `AddressFieldInput` .
- `AddressInput` => `AddressFieldInput` .
- `ChainedSelectInput` => `ChainedSelectFieldInput` .
- `CheckboxInput` => `CheckboxFieldInput` .
- `CheckboxInput` => `CheckboxFieldInput` .
- `EmailInput` => `EmailFieldInput` .
- `FormsSortingInput` => `FormsSortDirectionInput` .
- `ListInput` => `ListFieldInput` .
- `NameInput` => `NameFieldInput` .
- `PostImageInput` => `PostImageFieldInput` .

### Object Type Names
- `Button` => `FormButton` .
- `LastPageButton` => `FormLastPageButton` .

### Type fields.
- Query/Mutation arguments: `(resumeToken: String)` => `(id: ID, idType: RESUME_TOKEN)` . **Note:** In preparation for being able to query draft entries directly.
- `GravityFormsEntry { entryId }` => `GravityFormsEntry { databaseId }` . **Note:** Best Practice. Will continue to exist in deprecated form until WPGraphQL removes theirs. Draft entries will continue to use `resumeToken`.
- `EntryQuizResults { isPass }` => `EntryQuizResults { isPassingScore}` .
- `GravityFormsForm { enableAnimation }` => `GravityFormsForm { isAnimationEnabled }` .
- `GravityFormsForm { enableHoneypot }` => `GravityFormsForm { isHoneypotEnabled }` .
- `GravityFormsForm { enableHoneypot }` => `GravityFormsForm { isHoneypotEnabled }` .
- Form Limit Entry Settings:

```diff
GravityFormsForm {
-	limitEntries:
-	limitEntriesCount
-	limitEntriesMessage
-	limitEntriesPeriod
+	entryLimitSettings {
+		hasEntryLimit
+		maxEntries
+		limitReachedMessage
+		limitationPeriod
+	}
}
```

- Form Post Creation

```diff
GravityFormsForm {
-	postAuthor: Int
-	postCategory: Int
-	postContentTemplate
-	postContentTemplateEnabled
-	postFormat: String
-	postStatus: String
-	postTitleTemplateEnabled
-	postTitleTemplate
-	useCurrentUserAsAuthor
+	postCreationSettings{
+		postAuthorId: Int
+		postAuthor: User
+		postCategoryId: Int
+		postCategory: Taxonomy
+		postContentTemplate
+		hasPostContentTemplate
+		postFormat: Enum
+		postStatus: Enum
+		hasPostTitleTemplate
+		postTitleTemplate
+		isCurrentUserSetAsAuthor
+	}
}
```

- Form Login Settings

```diff
GravityFormsForm {
-	requireLogin
-	requireLoginMessage
+	loginSettings {
+		isLoginRequired
+		loginRequiredMessage
+	}
}
```

- Form Save & Continue

```diff
GravityFormsForm {
-	save {
+	saveAndContinue {
-		enabled
+		isSaveAndContinueEnabled
		buttonText
-	}
}
```

- Form Scheduling Settings

```diff
GravityFormsForm {
-	scheduleEnd
-	scheduleEndAmpm: String
-	scheduleEndHour
-	scheduleEndMinute
-	scheduleForm
-	scheduleMessage
-	schedulePendingMessage
-	scheduleStart
-	scheduleStartAmpm: String
-	scheduleStartHour
-	scheduleStartMinue
+	scheduleSettings {
+		hasSchedule
+		closedMessage
+		pendingMessage
+		startDetails : ScheduleDetails {
+			date
+			hour
+			minute
+			amPm: Enum
+		}
+		endDetails : ScheduleDetails {}
+	}
}
```
- `GravityFormsForm { validationSummary }` => `GravityFormsForm { isValidationSummaryEnabled }` .
- `FormNotification { disableAutoformat }` => `FormNotification { isAutoformatDisabled }` .
- `FormNotification { enableAttachments }` => `FormNotification { isAttachmentSendingEnabled }` .
- `FormPagination { displayProgressbarOnConfirmation }` => `ForPagination { hasProgressarOnConfirmation }` .
- Form Quiz Settings
```diff
QuizSettings {
-	shuffleFields
+	isShuffleFieldsEnabled
-	instantFeedback
+	hasInstantFeedback
-	passfailDisplayConfirmation
+	isPassFailConfirmationEnabled
-	letterDisplayConfirmation
+	isLetterConfirmationEnabled
-	passConfirmationMessage
-	passConfirmationDisableAutoformat
-	failConfirmationMessage
-	failConfirmationDisableAutoformat
-	letterConfirmationMessage
-	letterConfirmationDisableAutoformat
+	passConfirmation : QuizConfirmation {
+		isAutoformatEnabled
+		message
+	}
+	failConfirmation: QuizConfirmation {}
+	letterConfirmation: QuizConfirmation {}
}
```
- `FormField { allowsPrepopulate }` => `FormField { isPrepopulationEnabled }` .
- `FormField { chainedSelectsHideInactive }` => `FormField { isInactiveChainedSelectsHidden }` .
- `FormField { chainedSelectsHideInactive }` => `FormField { isInactiveChainedSelectsHidden }` .
- `FormField { copyValuesOptionDefault }` => `FormField { isCopyValueOptionsDefaultEnabled }` .
- `FormField { copyValuesOptionDefault }` => `FormField { isCopyValueOptionsDefaultEnabled }` .
- `FormField { disableMargins }` => `FormField { hasMargins }` .
- `FormField { displayAllCategories }` => `FormField { hasAllCategories }` .
- `FormField { displayAlt }` => `FormField { hasAlt }` .
- `FormField { displayCaption }` => `FormField { hasCaption }` .
- `FormField { displayDescription }` => `FormField { hasDescription }` .
- `FormField { displayTitle }` => `FormField { hasTitle }` .
- `FormField { emailConfirmEnabled }` => `FormField { hasEmailConfirmation }` .
- `FormField { enableAutocomplete }` => `FormField { hasAutocomplete }` .
- `FormField { enableCalculation }` => `FormField { isCalculation }` .
- `FormField { enableChoiceValue }` => `FormField { hasChoiceValue }` .
- `FormField { enableColumns }` => `FormField { hasColumns }` .
- `FormField { enableColumns }` => `FormField { hasColumns }` .
- `FormField { enableCopyValuesOption }` => `FormField { isCopyValueOptionsEnabled }` .
- `FormField { enableEnhancedUI }` => `FormField { hasEnhancedUI }` .
- `FormField { enableOtherChoice }` => `FormField { hasOtherChoice }` .
- `FormField { enablePasswordInput }` => `FormField { isPasswordInput }` .
- `FormField { enablePrice }` => `FormField { hasPrice }` .
- `FormField { enableRandomizeQuizChoices }` => `FormField { isRandomizeQuizChoicesEnabled }` .
- `FormField { enableSelectAll }` => `FormField { hasSelectAll }` .
- `FormField { enableWeightedScore }` => `FormField { hasWeightedScore }` .
- `FormField { multipleFiles }` => `FormField { isMultipleFilesEnabled }` .
- `FormField { noDuplicates }` => `FormField { isNoDuplicatesEnabled }` .
- `FormField { passwordStrengthEnabled }` => `FormField { isPasswordStrengthEnabled }` .
- `FormField { postFeaturedImage }` => `FormField { hasFeaturedImage }` .
- `FormField { showAnswerExplanation }` => `FormField { isAnswerExplanationShown }` .
- `FormField { useRichTextEditor }` => `FormField { isRichTextEditorEnabled }` .

**Comment by natac13** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Changing GF Field Names in the API](https://trello.com/c/vJ84R8xY/949-changing-gf-field-names-in-the-api)

**Comment by natac13** [comment]
>if we're already removing so much deprecated code (and making other breaking changes in the process), it might make sense to remove the old values entirely (i.e. ripping the bandaid off).

Agreed!
