### ISSUE TITLE
[Bug] PHP Notice:  Trying to access array offset on value of type bool in /../wp-content/plugins/wp-graphql-gravity-forms/src/Type/Enum/PostFormatTypeEnum.php on line 44

### ISSUE THREAD

**Issue by justlevine** [harness-software/wp-graphql-gravity-forms#210]
https://github.com/harness-software/wp-graphql-gravity-forms/blob/e58ae7c5c4e4be99cf24e5f07ed9fc7e0314e1a8/src/Type/Enum/PostFormatTypeEnum.php#L44

We need to be checking if `post_formats` is an array before iterating through it.

h/t [ebelanger](https://wp-graphql.slack.com/archives/C3NM1M291/p1642518328072400?thread_ts=1639599817.489800&cid=C3NM1M291)

**Comment by noshoesplease** [comment]
```
if($post_formats && $post_formats[0]) {
			foreach ( $post_formats[0] as $type ) {
				$values[ WPEnumType::get_safe_name( $type ) ] = [
					'value'       => $type,
					// translators: Post format.
					'description' => sprintf( __( 'A %s post format.', 'wp-graphql-gravity-forms' ), $type ),
				];
			}
		}
```

this worked for me
