### ISSUE TITLE
submitGfForm mutation entry returns null even though form gets submitted

### ISSUE THREAD

**Issue by IlirBajrami** [harness-software/wp-graphql-gravity-forms#221]
Here's a reproducible example for the case: https://codesandbox.io/s/recursing-darkness-xogm66?file=/components/GravityFormsField.js

**Comment by justlevine** [comment]
If I'm understanding your code, youre logging the `state` which is simply the form/field values, not the mutation response.

**Comment by justlevine** [comment]
In your codesandbox, check your errors response. You're not submitting required fields:

![Screenshot_20220216-173442.png](https://user-images.githubusercontent.com/29322304/154299255-3b4ff54e-6ba3-475f-aaa1-75ff15f6cfad.png)

**Comment by justlevine** [comment]
These seems to be very much an Apollo issue with `useMutation()`. Sorry I
can't be more help.
