### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PudparK** [harness-software/wp-graphql-gravity-forms#24]
I'm getting the following error. I could be installing it incorrectly. I installed the entire repo, but thought I should only install the src files? Not sure.
`Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in /home/c132grap/staging/1/wp-content/plugins/wp-graphql-gravity-forms-master/src/WPGraphQLGravityForms.php on line 180
`

**Comment by kellenmace** [comment]
Hey @PudparK 👋

As stated in the readme, the project requires PHP 7.4+. Based on the error output you provided, I think you're likely on a version lower than 7.4. Can you please update your product to PHP 7.4, if possible, then try again?

In terms of installing the plugin, you can either:

1. Use [Composer](https://getcomposer.org/) and run `composer require harness-software/wp-graphql-gravity-forms` to include it in your project.
2. Download the plugin from GitHub, making sure the directory name is "wp-graphql-gravity-forms" (sometimes GitHub likes to add "-master" to the end of it), then move the entire directory into your WP plugins directory (so not just the /src directory, like you mentioned).

Please let me know if I can help out with anything else!

Thanks, Kellen

**Comment by PudparK** [comment]
Ah yes, the one thing I didn't try. 🤦🏽‍♂️
If I can ask two questions:
- I'm working a on a GatsbyJS site, can I upload images as part of a form entry using this plugin?
- Does the PayPal functionality work with this plugin?

**Comment by kellenmace** [comment]
No, unfortunately, the plugin doesn't support file/image uploads at this point. Nor is there consensus in the GraphQL community on a standardized way to handle file uploads. That's part of the reason why the WPGraphQL plugin doesn't currently have a mutation for saving images from multipart form data to the WP Media Library (though it does have the ability to sideload images into the Media Library from external URLs).

You could do this:
- Write a custom mutation that accepts a base-64 encoded string as an input argument, and that base-64 decodes  that string back into a file, saves it to the proper Gravity Forms uploads directory, then returns a success response.
- Then on the client, once the user selects the images to uploaded, base-64 encode them into strings and fire off your custom mutation to save them.

Alternatively, you could take a look at the [Gravity Forms REST API](https://docs.gravityforms.com/rest-api-v2/) and see if handling form submissions that way makes sense for your project.

This plugin supports the field types you can see here: https://github.com/harness-software/wp-graphql-gravity-forms/tree/master/src/Mutations. If the PayPal functionality only requires those fields, then you may be able to get it working. I assume you want to be able to render out credit card input fields, though -- the plugin doesn't support those currently.

Hopefully that info is helpful! Best of luck.

**Comment by PudparK** [comment]
Thank you so much for the helpful response. This is exactly what I needed to hear. Hopefully, I'll be able to contribute more in the near future. Nice blog btw!

**Comment by kellenmace** [comment]
Sure thing.

Cool! – I welcome any contributions. And thanks 😊
