### ISSUE TITLE
[Feature Request] - Add normal/invisible reCaptcha type to CaptchaField object

### ISSUE THREAD

**Issue by shivapoudel** [harness-software/wp-graphql-gravity-forms#249]
Just need some queries to fetch reCAPTCHA v2 normal or invisible mode is activate on Gravity forms so we can code it on Next,js accordingly, my friend :)

**Comment by justlevine** [comment]
hey @shivapoudel 
Support for reCaptcha validation was [added in `v0.11.0`](https://github.com/harness-software/wp-graphql-gravity-forms/releases/tag/v0.11.0).
What specifically are you to achieve?

**Comment by justlevine** [comment]
The `captchaType` is available on the formField to let you conditionally load the correct reCaptcha script. Once you get the token from reCaptcha, you [pass it as part of the fieldValues input on the mutation](https://github.com/harness-software/wp-graphql-gravity-forms/blob/develop/docs/submitting-forms.md#captcha-validation).

**Comment by shivapoudel** [comment]
![image](https://user-images.githubusercontent.com/3774827/163427837-167ed2de-083e-4a96-9f93-ab7b4ac6ff30.png)

I tried to perform query with this:
```
          ... on CaptchaField {
            id
            captchaType
          }
```

But I always get 

```
          {
            "node": {
              "id": 8,
              "captchaType": "RECAPTCHA" <--- On Checkbox as well as Invisible type.
            }
          }
```

**Comment by justlevine** [comment]
Thanks for clarifying, that does seem to be an oversight!
(PS: I removed your screenshot. **Never** share your API secrets publicly!)

**Comment by robmarshall** [comment]
@justlevine Seems that the `gfSettings` object is not accessible when pulling with Gatsby. Is it private?

**Comment by justlevine** [comment]
@robmarshall It's public, can't think of anything that would be getting in the way of Gatsby. Can you open up a new issue so it doesn't get lost here, and I'll investigate?
