### ISSUE TITLE
File upload issue

### ISSUE THREAD

**Issue by cpramod** [harness-software/wp-graphql-gravity-forms#250]
I am trying to upload image file $_FILES and passed the file in this format: 
{
            "id": 8,
            "fileUploadValues": {
                "name": "Rataplan-straatzijde_20180328_EW46474_PHOTO-©-EDDY-WESTVEER-1024x576.jpeg",
                "type": "image/jpeg",
                "size": 162024,
                "tmp_name": "/var/folders/h6/2h8fnrtx1q7ddt18hm162_k80000gn/T/upload_a0051c2799aa83484fc63ae57ffc7a0f"
            }
        } 

but it throw this error: Field "submitGfForm" argument "input" requires type Upload!

**Comment by justlevine** [comment]
Hey @cpramod ,

How exactly are you passing that input to graphQL?
For some reason, WPGraphQL Upload requires an `Upload` _object_, and not a generic object with the same required properties.

The difference is that you need to _first_ define `const myFileUpload = { name, size, type, tmp_name}` and then pass the object to `fileUploadValues`. Similarly, in GraphiQL, you should define the input in the bottom, and then pass it as a variable to the mutation ( i.e. `mutation myMutation( $myFile: Upload ){}`).

Also pretty sure you're required to pass it as an array of objects (` fileUploadValues: [ $myFile ] `)

**Comment by cpramod** [comment]
Thank you
