### ISSUE TITLE
File input upload does not return tmp_name or temp_filename

### ISSUE THREAD

**Issue by shalawfatah** [harness-software/wp-graphql-gravity-forms#252]
I have a Wordpress headless CMS with GatsbyJS frontend. I have installed WPGraphQL, WPGraphQL for Gravity Froms, and WP GraphQL File Upload to use the gravity forms to send a form from the frontend to the backend, it has some photos with it.

Here is the list of my WP plugins: 
```
​​ACF Content Analysis for Yoast SEO
Add WPGraphQL SEO
AddToAny Share Buttons
Advanced Custom Fields PRO
Gravity Forms
Gravity Forms Mailchimp Add-On
Jetpack
Redirection
Safe SVG
Soil
User Role Editor
WP All Import - ACF Add-On
WP All Import Pro
WP Gatsby
WP GraphQL
WP GraphQL Gutenberg
WP Quiz
WPGraphQL for Advanced Custom Fields
WPGraphQL for Gravity Forms
WPGraphQL Upload
Yoast SEO
```

Here is a list of Gatbsy plugins and libraries:

```
"dependencies": {
   "@apollo/client": "^3.5.10",
   "@hookform/resolvers": "^2.8.8",
   "beautiful-react-hooks": "^1.2.0",
   "cross-fetch": "^3.1.5",
   "gatsby": "4.6",
   "gatsby-plugin-add-filters": "^1.0.0",
   "gatsby-plugin-google-tagmanager": "4.6",
   "gatsby-plugin-image": "2.6",
   "gatsby-plugin-manifest": "4.6",
   "gatsby-plugin-offline": "5.6",
   "gatsby-plugin-react-helmet": "5.6",
   "gatsby-plugin-react-leaflet": "^3.0.3",
   "gatsby-plugin-sass": "5.6",
   "gatsby-plugin-sharp": "4.6",
   "gatsby-source-filesystem": "4.6",
   "gatsby-source-wordpress": "6.6",
   "gatsby-transformer-sharp": "4.6",
   "jotai": "^1.6.1",
   "leaflet": "^1.7.1",
   "leaflet.locatecontrol": "^0.76.0",
   "react": "^17.0.2",
   "react-dom": "^17.0.2",
   "react-helmet": "^6.1.0",
   "react-hook-form": "^7.26.0",
   "react-icons": "^4.3.1",
   "react-images": "^1.2.0-beta.7",
   "react-leaflet": "^3.2.5",
   "react-leaflet-markercluster": "^3.0.0-rc1",
   "react-photo-gallery": "^8.0.0",
   "react-share": "^4.4.0",
   "sass": "^1.49.7",
   "swiper": "^8.0.6"
 },

When I use a switch statement to show all my form fields, it shows them all, the file upload shows it all as well. 
This is my fileuploadfield fragment
export const FileUploadField = graphql`
 fragment FileUploadField on WpFileUploadField {
   isRequired
   label
   id
   type
   value
   errorMessage
   description
   cssClass
 }
`;
```

However, when I try to upload a photo, it does not return tmp_name. Here is what I get in the console:

```
Some image > file [0]
<img width="732" alt="Screen Shot 2022-04-22 at 5 03 03 PM" src="https://user-images.githubusercontent.com/56219053/164881218-f258aa7c-2c6d-4499-8ee9-f24eab2a59de.png">

name: something
size: something
type: something
relativePath: ""
```
Even after creating a path and temp_name manually, while it submits the form to the backend, the backend also cannot find the picture, saying:

```
2022-04-12 16:42:59.881352 - DEBUG --> GFFormDisplay::process_form(): After validation. Is submission valid? Yes. 
2022-04-12 16:42:59.881381 - DEBUG --> GFFormDisplay::process_form(): Uploading files... 
2022-04-12 16:42:59.881419 - DEBUG --> GFFormDisplay::upload_files(): Upload path /nas/content/live/guidedby2/wp-content/uploads/gravity_forms/3-38f36a3cba1cdc80c6ddcf1d6664e72f 
2022-04-12 16:42:59.881530 - DEBUG --> GFFormsModel::get_temp_filename(): Uploaded filename is Image from iOS.jpg and temporary filename is 62560e83d7361_input_76.jpg 
2022-04-12 16:42:59.881560 - DEBUG --> GFFormDisplay::upload_files(): Temp file info: Array
(
    [uploaded_filename] => Image from iOS.jpg
    [temp_filename] => 62560e83d7361_input_76.jpg
)
 
2022-04-12 16:42:59.881588 - ERROR --> GFFormDisplay::upload_files(): File could not be uploaded: tmp_name: undefined - target location: /nas/content/live/guidedby2/wp-content/uploads/gravity_forms/3-38f36a3cba1cdc80c6ddcf1d6664e72f/tmp/62560e83d7361_input_76.jpg
```

As you can see, the form is submitted and files are uploaded (although I can’t find the photos anywhere on WP), but since tmp_name or temp_filename is not present, Gravity Forms cannot find them. I have no way of assigning tmp_name or temp_filename because if I attach that to the form submission, the form says such field does not exist. I have tried to make tmp_name to be a manual URL and regular name, but it seems does not work because tmp_name is assigned by the server randomly and it always changes. All permissions are open from the server to upload images.

**Comment by justlevine** [comment]
You seem to have excluded the Bug report template, which details the information we need to diagnose and resolve this...

>However, when I try to upload a photo, it does not return tmp_name. Here is what I get in the console:

Please share some _actual code_ (ideally something reproduceable with everything but WPGraphQL, WPGraphQL for Gravity Forms, WPGraphQL Upload, and Gravity Forms disabled).

Specifically, I need:
- The mutation graphql code. ( e.g. `  ```graphql mutation { submitGfForm( id: 1, fieldValues: {...} , ...){..}``` `
- The `fieldValues` array that is passed to the mutation input _and_ a console log of their values and sub values. Make sure to include the specifics of both for `fileUploadValues: $FileValues` as well.

Also, you are missing most of the required information from the bug report template:
* WordPress version:
* WPGraphQL version:
* Gravity Forms version:
* WPGraphQL for Gravity Forms version:

And it would probably also be helpful if you shared what environment WP is running on (OS version, PHP version, local or hosted, if it's in a dockerized container, etc).

**Comment by shalawfatah** [comment]
Okay, here is the four files requested
1. Debugging report from gravity forms in
2. Form rendering page and field Values In Form.tsx
3. Form submission mutation
4. form data in the console when you hit submit
5. System report:
--- hosting WP: on WP Engine
--- hosting Gatsby: on Gatsby Cloud
--- PHP: 7.4.1
--- database: 

MYSQL 8.1.16
---  WP Version: 5.9.2
--- Web server: nginx
Please let me know if anything else is needed

[bug_report_gravity_forms.pdf](https://github.com/harness-software/wp-graphql-gravity-forms/files/8548526/bug_report_gravity_forms.pdf)
[form_data_in_console.txt](https://github.com/harness-software/wp-graphql-gravity-forms/files/8548527/form_data_in_console.txt)
[form_mutation.txt](https://github.com/harness-software/wp-graphql-gravity-forms/files/8548528/form_mutation.txt)
[Form.txt](https://github.com/harness-software/wp-graphql-gravity-forms/files/8548529/Form.txt)

**Comment by justlevine** [comment]
As expected, you are not passing a valid `tmp_name` to the `fileUploadValues` input.

**There is no way to get the server's tmp path from the JS file object!** Here is a [list of the available properties](https://developer.mozilla.org/en-US/docs/Web/API/File#instance_properties).

As such mutation input should look like this:
```js
const tmpPath = '/tmp'; // change this to your specific server's tmp path.
...

const = fieldValues {
 ...other field values,
 ...( data["Profile Hero Image"][0].length > 0 ) && { // there's a difference between an empty field, and a field value with missing properties.
  id: 76,
  fileUploadValues: [
    {
      name: data["Profile Hero Image"][0].name,
      type: data["Profile Hero Image"][0].type,
      size: data["Profile Hero Image"][0].size,
      tmp_name: `${tmpPath}/${data["Profile Hero Image"][0].name}`, // outputs to /tmp/myProfilePick.jpg
    },
  ],
};
```

If you're unsure of what your server's tmp path is, you can stick the following line in your WP's `functions.php`, and check the debug log:
```php
error_log( 'Temp filepath: ' . sys_get_temp_dir() );
```

**Comment by shalawfatah** [comment]
@justlevine yet let's say I find the temp folder, I still do not know how to get the `tmp_name`, and I tested it with an imaginary tmp_name like `tmp_name: ${tmpPath}/${data["Profile Hero Image"][0].tmp_name}` but the property does not exist on that object. that's why I used name, because with name, at least the form is submitted. I still do not know the answer for how to get the tmp_name in the first place.

**Comment by justlevine** [comment]
@shalawfatah did you already try `/tmp`?

Please read the last sentence of my previous reply. It's a static path on your server, and you find out what it is by using that function and checking what gets logged. Then use that path + the name in the frontend.

Or, just ask WPEngine what your tmp path is and use that.

**Comment by shalawfatah** [comment]
@justlevine I'll do that, to be honest debug file is so big it crashes my computer when I open it. But I'll find a way. My problem is the path can be found, but the temporary name assigned by the server cannot be found, but thanks for the help, I'll do as you said and let you know.

**Comment by justlevine** [comment]
>  debug file is so big it crashes my computer when I open it.

Just delete the file and it will regenerate.

> My problem is the path can be found, but the temporary name assigned by the server cannot be found, but thanks for the help

Great, so step one use that path as the first part. I'm pretty sure you provide any name, and that is what will be used _so long as its unique to the folder_ (ie using the original file name will work the first time, but not if its reuploaded). Just generate a random string and you should be fine.

**Comment by shalawfatah** [comment]
@justlevine the temp folder seems to be the tmp folder only.
`[24-Apr-2022 02:55:55 UTC] Temp filepath: /tmp`
so I wired it like this, unfortunately now when I upload images, and submit, it gives me this `internal server error` without much explanation. 

```
One unhandled runtime error found in your files. See the list below to fix it:
Error in function new ApolloError in ./node_modules/@apollo/client/errors/index.js:29
Internal server error
./node_modules/@apollo/client/errors/index.js:29
```

When checking the error in the vs code, it's this: 

```
var ApolloError = (function (_super) {
    __extends(ApolloError, _super);
    function ApolloError(_a) {
        var graphQLErrors = _a.graphQLErrors, clientErrors = _a.clientErrors, networkError = _a.networkError, errorMessage = _a.errorMessage, extraInfo = _a.extraInfo;
        var _this = _super.call(this, errorMessage) || this;
        _this.graphQLErrors = graphQLErrors || [];
        _this.clientErrors = clientErrors || [];
        _this.networkError = networkError || null;
        _this.message = errorMessage || generateErrorMessage(_this);
        _this.extraInfo = extraInfo;
        _this.__proto__ = ApolloError.prototype;
        return _this;
    }
    return ApolloError;
}(Error));
export { ApolloError };
//# sourceMappingURL=index.js.map
```

**Comment by justlevine** [comment]
Internal server errors are output to debug.log

**Comment by shalawfatah** [comment]
Strange thing when I push to Gatsby Cloud, the website, which you can check here, `https://guidedbyreactdevelop07035.gatsbyjs.io/ ` does not allow sending the form, the console says, ` Field "fileUploadValues" is not defined by type FormFieldValuesInput at value[22] `, but on `localhost`, it does send the form but the image still cannot be copied saying, 
```
2022-04-23 23:40:55.507333 - DEBUG --> GFFormDisplay::process_form(): After validation. Is submission valid? Yes. 
2022-04-23 23:40:55.507369 - DEBUG --> GFFormDisplay::process_form(): Uploading files... 
2022-04-23 23:40:55.507421 - DEBUG --> GFFormDisplay::upload_files(): Upload path /nas/content/live/guidedby2dev/wp-content/uploads/gravity_forms/4-67224dde2a1146bcc1307f9cb6971361 
2022-04-23 23:40:55.507505 - DEBUG --> GFFormsModel::get_temp_filename(): Uploaded filename is some-png-file.png and temporary filename is 6264f0f77be54_input_76.png 
2022-04-23 23:40:55.507549 - DEBUG --> GFFormDisplay::upload_files(): Temp file info: Array
(
    [uploaded_filename] => some-png-file.png
    [temp_filename] => 6264f0f77be54_input_76.png
)
 
2022-04-23 23:40:55.507586 - ERROR --> GFFormDisplay::upload_files(): File could not be uploaded: tmp_name: /tmp/some-png-file.png - target location: /nas/content/live/guidedby2dev/wp-content/uploads/gravity_forms/4-67224dde2a1146bcc1307f9cb6971361/tmp/6264f0f77be54_input_76.png 
2022-04-23 23:40:55.507632 - DEBUG --> GFFormsModel::get_temp_filename(): Uploaded filename is tree-736885__480.jpeg and temporary filename is 6264f0f77be54_input_77.jpeg 
2022-04-23 23:40:55.507663 - DEBUG --> GFFormDisplay::upload_files(): Temp file info: Array
```

**Comment by justlevine** [comment]
> Strange thing when I push to Gatsby Cloud, the website, which you can check here, https://guidedbyreactdevelop07035.gatsbyjs.io/ does not allow sending the form, the console says, Field "fileUploadValues" is not defined by type FormFieldValuesInput at value[22]

That sounds like a tech support issue and not an issue with the plugin, but double check that it WPGraphQL Upload is actually enabled on the live server.

> on localhost, it does send the form but the image still cannot be copied.

Clear your /tmp folder, run the mutation, and then `ls -la /tmp` to see what file name _does_ get uploaded to the server.

**Comment by justlevine** [comment]
Alternative approach,
1. add `apollo-upload-client` to the project.
2. when you define the ApolloClient, set the upload link:
```js
import { ApolloClient, InMemoryCache } from "@apollo/client";
import { createUploadLink } from "apollo-upload-client";

const myEndpoint = "https://wp.test/wp/graphql"

const client = new ApolloClient({
  uri: myEndpoint,
  cache: new InMemoryCache(),
	link: createUploadLink({
		uri: myEndpoint
	}),
});

export default client;
```

In your mutation, pass the file object directly, no worry about the tmp or destructuring:
```js
...
 fileUploadValues: [ data["Profile Hero Image"][0] ],
...
```

**Comment by shalawfatah** [comment]
Thanks @justlevine the alternative approach which is using `apollo-upload-client` actually worked. I will close down this issue.

**Comment by justlevine** [comment]
Hey @OJDhiman 

Please open up a new issue with all the information that the template requests, so we can give this the full attention it deserves.

My gut is like with this issue, you're not passing all the properties required by the `Upload` scalar (see the relevant row in [this table](https://github.com/harness-software/wp-graphql-gravity-forms/blob/develop/docs/submitting-forms.md).

Easiest way to do this (since tmp_name is path + name on the _server_ which can change based on your env) is to use the `apollo-upload-client` package, and then pass the generated js `File` object directly to the array, as [described above](https://github.com/harness-software/wp-graphql-gravity-forms/issues/252#issuecomment-1107873528)
