### ISSUE TITLE
Add confirmation data to `submitGfEntry` mutation response.

### ISSUE THREAD

**Issue by justlevine** [harness-software/wp-graphql-gravity-forms#256]
### Discussed in https://github.com/harness-software/wp-graphql-gravity-forms/discussions/255

h/t @koduvaal

Tl;Dr instead of having to recreate the `conditionalLogic` post entry, we should be able to return the correct confirmation directly on the mutation response.

This would also solve the bad DX currently where there is no success indicator only `errors`.

**Comment by KoduVaal** [comment]
thanks @justlevine ,
Do you have any timeline on this to get released? that will help us on completing our work. since this doesn't break anything, it is possible to add it hotfix?

**Comment by justlevine** [comment]
Hotfixes are reserved for bugs _caused_ by the previous release, but you can track the progress towards the next minor release [here](https://github.com/harness-software/wp-graphql-gravity-forms/milestone/11).
