### ISSUE TITLE
version 0.11.1 update error

### ISSUE THREAD

**Issue by idesignzone** [harness-software/wp-graphql-gravity-forms#267]
### Description

I am trying to update from 0.1.0 to 0.1.1 via WP admin but get this error

### Steps to reproduce

Update from 0.1.0 to 0.1.1 via WP admin
error: Update failed: The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature

### Plugin Version

0.1.1

### Gravity Forms Version

0.1.1

### WordPress Version

6.0

### WPGraphQL Version

1.8.2

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for RankMath SEO, WPGraphQL, and WPGraphQL for Rank Math

- [X] Yes
- [ ] My issue is with a specific 3rd-party plugin.

**Comment by justlevine** [comment]
Thanks for reporting this @idesignzone !

If you add `define( 'WP_DEBUG_LOG', true );` to your wp-config.php and check `debug.log` do you see anything else?

**Comment by justlevine** [comment]
Hey @idesignzone if you go and Check for Updates, you should see a hotfixed `v0.11.1.1` that should install just fine 🤞.

Thanks for reporting this, and let us know if the new release doesn't work and we'll reopen this issue.
