### ISSUE TITLE
Question: Support for additional fields

### ISSUE THREAD

**Issue by westende** [harness-software/wp-graphql-gravity-forms#27]
Hi. We are checking out this plugin. We notice that additional fields such as GravityForms' own poll field are not supported. Would you be open to support these from this plugin or would you like to keep that in separate WordPress plugins?

**Comment by justlevine** [comment]
Consent and Survey fields are missing too.

**Comment by tinytoolbox** [comment]
Sorry for the delayed response.  Poll & Survey fields were low priorities for us at the outset which is why we haven't added them but we'd like to eventually support them.  Consent fields are likely to be added soon.  Feel free to contribute!

**Comment by justlevine** [comment]
Closing in favor of #119
