### ISSUE TITLE
500 error after activating plugin

### ISSUE THREAD

**Issue by DimaBur** [harness-software/wp-graphql-gravity-forms#3]
After activating plugin <mysite>/graphql endpoint doesn't work. It responces 500 error. 
Dependencies: 
- WP GraphQL 0.3.6
- Gravity Forms 2.3.0.4

When I deactivating it, everything works fine. And I can query graphql.

**Comment by kellenmace** [comment]
@DimaBur Can you please try again with the latest versions of both plugins? It should work. Please also make sure you're running PHP 7. If you still get a 500 error after that, please check your server logs or turn on debug logging and create a new issue, pasting in the text from the error message. Thanks.
