### ISSUE TITLE
Unclear Documentation :  List fields

### ISSUE THREAD

**Issue by TomDoFuture** [harness-software/wp-graphql-gravity-forms#326]
### Description

https://github.com/harness-software/wp-graphql-gravity-forms/blob/develop/docs/submitting-forms.md

If you see the example of listvalues implementation, the value inside List values is not an array of objects but a singular objects,

I am sure it has to be a list of objects, which each object representing a row, and inside the rowValues you have the column values.

### Steps to reproduce

read the docs

### Plugin Version

NA

### Gravity Forms Version

NA

### WordPress Version

NA

### WPGraphQL Version

NA

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for Gravity Forms, WPGraphQL, and WPGraphQL for Gravity Forms

- [ ] Yes
- [ ] My issue is with a specific 3rd-party plugin.

**Comment by justlevine** [comment]
Hey @TomDoFuture 

As shown in the table, `listValues` does indeed take an array of `rowValues`. However in GraphQL, you can skip the brackets if you're only submitting a single item in an array. So `listValues: { rowValues: "my submitted value" }` is the same as `listValues: [ { rowValues: [ "my submitted value"] } ]`.

My intent for the example queries was to show as many different possible syntaxes as concisely as possible, and as multiple array objects was already covered by `chainedSelectValues` and `checkboxValues`, I thought `listValues` would be a good way to highlight the shorthand sytanx, but perhaps its not worth the confusion....

**Comment by TomDoFuture** [comment]
Hello @justlevine 

To kill all confusion and keep the best of both worlds, make it in an array like [{rowValues : ["bla bla"]}]. , then put a comment like. #If single item can be singular object {rowValues : ['lol]}
