### ISSUE TITLE
[Bug] missing file platform_check.php (plugins/wp-graphql-gravity-forms/vendor/composer/platform_check.php)

### ISSUE THREAD

**Issue by kenseito** [harness-software/wp-graphql-gravity-forms#42]
## Describe the bug
Fatal error: require(): Failed opening required '/var/www/html/web/app/plugins/wp-graphql-gravity-forms/vendor/composer/platform_check.php' (include_path='.:/usr/local/lib/php') in /var/www/html/web/app/plugins/wp-graphql-gravity-forms/vendor/composer/autoload_real.php on line 25

## To Reproduce
When installing the plugin using composer and navigating to the wordpress site, I encountered the above error. I checked for the vendor/composer/platform_check.php file but it is not there.

https://github.com/harness-software/wp-graphql-gravity-forms/blob/ee26f46db31f087fc6d8a4003b6ad80de778bfa5/vendor/composer/autoload_real.php#L25

### Technical Info
* WordPress version: 5.6
* WPGraphQL version: 1.1.3
* Gravity Forms version: 2.4.22.5
* WPGraphQL for Gravity Forms version: 'main'
* Composer version 1.10.5

**Comment by justlevine** [comment]
Hang tight @kenseito - we're in the process cleaning up the repository, and should have everything working as it should (and creating a new branch for development) shortly.

Just to verify, how did you add the plugin using composer? And if you manually grab the zip and upload it, do you have the same error?

**Comment by kenseito** [comment]
yes same error

I dropped it into a fresh wordpress installation as well
Fatal error: require(): Failed opening required '/wordpress/wp-content/plugins/wp-graphql-gravity-forms-main/vendor/composer/platform_check.php' (include_path='.:/usr/local/Cellar/valet-php@7.4/7.4.14/share/valet-php@7.4/pear') in /wordpress/wp-content/plugins/wp-graphql-gravity-forms-main/vendor/composer/autoload_real.php on line 25

**Comment by justlevine** [comment]
Just wanted to be sure. 
We just (this second) released v0.1.0, which includes the correct vendor and autoload files needed for production.

Reinstall and you should be good to go!

**Comment by kenseito** [comment]
Thank you. The plugin is loading now
although I had to add it this way
composer require harness-software/wp-graphql-gravity-forms:dev-main#0.1.0.release

Perhaps add the tag '0.1.0' as well to the commit?

**Comment by justlevine** [comment]
Sorry about that. We ran into a issue with GitHub (seems that tag was created ways back and even after deleting, GitHub was still associating it with the old data). 

The next release will go back to the normal naming convention (and be on packagist).  I'll ping you here, so you know when it's time to update the `composer require`.

**Comment by justlevine** [comment]
@kenseito just pushed v0.2.0, so the normal `composer require harness-software/wp-graphql-gravity-forms` should be working as expected, without the need for any branches/release numbers.
