### ISSUE TITLE
Sorry, you are not allowed to view Gravity Forms entries

### ISSUE THREAD

**Issue by tomhermans** [harness-software/wp-graphql-gravity-forms#5]
Activated gravityforms and this plugin, and have a few forms (with entries), but when doing this inside the GraphiQL env (within WP)
query myQuery {
  gravityFormsEntries {
    nodes {
      id
    }
  }
}

I get "Sorry, you are not allowed to view Gravity Forms entries". 

What am I missing or doing wrong ? Do I have to enable something in settings (can't seem to find anything either..)

**Comment by kellenmace** [comment]
@tomhermans Whenever the site receives a request for entries, a permissions check is performed to have sure there is a currently logged-in user who has the `gravityforms_view_entries` capability. If there isn't, then that error message is returned.

For testing, you can activate https://github.com/wp-graphql/wp-graphiql, then log into WP as a user who has the `gravityforms_view_entries` capability. Then any requests you fire off from the GraphiQL instance embedded in the WP admin will include your auth cookie, and you'll be able to run queries for Gravity Forms entries.

If you have a client-side app and want to be able to query for entries from there, then you'll need to set up authentication. This plugin works great if you want to use JSON web tokens for auth: https://github.com/wp-graphql/wp-graphql-jwt-authentication

Best of luck! 👍
